### ISSUE TITLE
Travis CI when public

### ISSUE THREAD

**Issue by enzy** [frontbase/Frontbase#10]
Config `.travis.yml`

``` yml
 language: node_js
 node_js:
   - "0.10"
   - "0.8"
   - "0.6"
```
